In [16]:
import torch
import torch.nn.functional as F

In [4]:
t = torch.randn(4)

In [5]:
t.mean(),t.std()

(tensor(-0.0482), tensor(0.8712))

In [6]:
r = torch.randn(4)

In [7]:
r

tensor([ 0.7519, -0.1986, -0.4822,  0.3983])

In [14]:
r = torch.tanh(r*0.0001)
r

tensor([ 7.5186e-09, -1.9860e-09, -4.8222e-09,  3.9826e-09])

In [17]:
F.softmax(r)

<ipython-input-17-f331cd1556d2>:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(r)


tensor([0.2500, 0.2500, 0.2500, 0.2500])